# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md","s3_website.yml"] # files to exclude
highlighter: pygments
markdown: kramdown
disqus: andreacfm
#google_analytics: dbyll
gems: [jekyll-paginate]

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Andrea's blog

description: Just my blog
author:
  name: andreacfm
  email: acampolnghi@gmail.com
  github: andreacfm
  twitter: ACampolonghi
  linkedin: andreacampolonghi
  #bio: Your stylish, minimalist theme!
  email_md5: fe88efa62f2b20bdeb8689626d375f1e

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:
